version: "3"

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: springvue
      MYSQL_USER: springvue
      MYSQL_PASSWORD: springvue00

  front:
    image: springvue/front
    restart: always
    ports:
      - 8080:8080

  back:
    image: springvue/back
    restart: always
    ports:
      - 9080:8080
